"""init

Revision ID: 875cf39ddf51
Revises: 
Create Date: 2026-03-27 11:26:34.437642
"""
from alembic import op
import sqlalchemy as sa


revision = '875cf39ddf51'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('upload_batch', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', 'date', name='uq_attendance')
    )
    op.create_index(op.f('ix_attendance_records_date'), 'attendance_records', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_records_id'), 'attendance_records', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_table('attendance_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('total_classes', sa.Integer(), nullable=True),
    sa.Column('classes_attended', sa.Integer(), nullable=True),
    sa.Column('attendance_pct', sa.Float(), nullable=True),
    sa.Column('is_below_75', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', name='uq_att_summary')
    )
    op.create_index(op.f('ix_attendance_summary_id'), 'attendance_summary', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_summary_student_id'), 'attendance_summary', ['student_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('target', sa.Float(), nullable=False),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('deadline', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('auto_tracked', sa.Boolean(), nullable=True),
    sa.Column('rule', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_table('internal_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('test_number', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('marks_scored', sa.Float(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', 'test_number', name='uq_internal')
    )
    op.create_index(op.f('ix_internal_tests_id'), 'internal_tests', ['id'], unique=False)
    op.create_index(op.f('ix_internal_tests_student_id'), 'internal_tests', ['student_id'], unique=False)
    op.create_table('placement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('section', sa.String(length=5), nullable=True),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('package_lpa', sa.Float(), nullable=True),
    sa.Column('offer_type', sa.String(length=30), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('upload_batch', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'company', name='uq_placement')
    )
    op.create_index(op.f('ix_placement_id'), 'placement', ['id'], unique=False)
    op.create_index(op.f('ix_placement_student_id'), 'placement', ['student_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=5), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('internal_marks', sa.Float(), nullable=True),
    sa.Column('external_marks', sa.Float(), nullable=True),
    sa.Column('total_marks', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.Column('has_arrear', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('upload_batch', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_code', 'semester', name='uq_result')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_index(op.f('ix_results_student_id'), 'results', ['student_id'], unique=False)
    op.create_index(op.f('ix_results_subject_code'), 'results', ['subject_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_results_subject_code'), table_name='results')
    op.drop_index(op.f('ix_results_student_id'), table_name='results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_placement_student_id'), table_name='placement')
    op.drop_index(op.f('ix_placement_id'), table_name='placement')
    op.drop_table('placement')
    op.drop_index(op.f('ix_internal_tests_student_id'), table_name='internal_tests')
    op.drop_index(op.f('ix_internal_tests_id'), table_name='internal_tests')
    op.drop_table('internal_tests')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_attendance_summary_student_id'), table_name='attendance_summary')
    op.drop_index(op.f('ix_attendance_summary_id'), table_name='attendance_summary')
    op.drop_table('attendance_summary')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_date'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
